/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TipoAtividadeService } from "../tipoAtividade.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TipoAtividadeCreateInput } from "./TipoAtividadeCreateInput";
import { TipoAtividadeWhereInput } from "./TipoAtividadeWhereInput";
import { TipoAtividadeWhereUniqueInput } from "./TipoAtividadeWhereUniqueInput";
import { TipoAtividadeFindManyArgs } from "./TipoAtividadeFindManyArgs";
import { TipoAtividadeUpdateInput } from "./TipoAtividadeUpdateInput";
import { TipoAtividade } from "./TipoAtividade";
import { ParticipacaoAtividadeFindManyArgs } from "../../participacaoAtividade/base/ParticipacaoAtividadeFindManyArgs";
import { ParticipacaoAtividade } from "../../participacaoAtividade/base/ParticipacaoAtividade";
import { ParticipacaoAtividadeWhereUniqueInput } from "../../participacaoAtividade/base/ParticipacaoAtividadeWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TipoAtividadeControllerBase {
  constructor(
    protected readonly service: TipoAtividadeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TipoAtividade",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TipoAtividade })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: TipoAtividadeCreateInput
  ): Promise<TipoAtividade> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        nome: true,
        tempoDuracao: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TipoAtividade",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [TipoAtividade] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(TipoAtividadeFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<TipoAtividade[]> {
    const args = plainToClass(TipoAtividadeFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        nome: true,
        tempoDuracao: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TipoAtividade",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TipoAtividade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: TipoAtividadeWhereUniqueInput
  ): Promise<TipoAtividade | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        nome: true,
        tempoDuracao: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TipoAtividade",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TipoAtividade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: TipoAtividadeWhereUniqueInput,
    @common.Body() data: TipoAtividadeUpdateInput
  ): Promise<TipoAtividade | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          nome: true,
          tempoDuracao: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "TipoAtividade",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TipoAtividade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: TipoAtividadeWhereUniqueInput
  ): Promise<TipoAtividade | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          nome: true,
          tempoDuracao: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ParticipacaoAtividade",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/participacaoAtividades")
  @ApiNestedQuery(ParticipacaoAtividadeFindManyArgs)
  async findManyParticipacaoAtividades(
    @common.Req() request: Request,
    @common.Param() params: TipoAtividadeWhereUniqueInput
  ): Promise<ParticipacaoAtividade[]> {
    const query = plainToClass(
      ParticipacaoAtividadeFindManyArgs,
      request.query
    );
    const results = await this.service.findParticipacaoAtividades(params.id, {
      ...query,
      select: {
        aluno: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        data: true,
        id: true,

        tipoAtividade: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "TipoAtividade",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/participacaoAtividades")
  async connectParticipacaoAtividades(
    @common.Param() params: TipoAtividadeWhereUniqueInput,
    @common.Body() body: ParticipacaoAtividadeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      participacaoAtividades: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "TipoAtividade",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/participacaoAtividades")
  async updateParticipacaoAtividades(
    @common.Param() params: TipoAtividadeWhereUniqueInput,
    @common.Body() body: ParticipacaoAtividadeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      participacaoAtividades: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "TipoAtividade",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/participacaoAtividades")
  async disconnectParticipacaoAtividades(
    @common.Param() params: TipoAtividadeWhereUniqueInput,
    @common.Body() body: ParticipacaoAtividadeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      participacaoAtividades: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
