import { StringFilter } from "../../util/StringFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntFilter } from "../../util/IntFilter";
import { OcorrenciaListRelationFilter } from "../ocorrencia/OcorrenciaListRelationFilter";
import { ParticipacaoAtividadeListRelationFilter } from "../participacaoAtividade/ParticipacaoAtividadeListRelationFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";

export type AlunoWhereInput = {
  cidade?: StringFilter;
  cpf?: StringFilter;
  dataEmissaoRg?: DateTimeNullableFilter;
  dataNascimento?: DateTimeFilter;
  dataSaida?: DateTimeNullableFilter;
  endereco?: StringNullableFilter;
  filiacaoMae?: StringFilter;
  filiacaoPai?: StringFilter;
  id?: StringFilter;
  idadeInicioDroga?: StringFilter;
  matricula?: IntFilter;
  nome?: StringFilter;
  ocorrencia?: OcorrenciaListRelationFilter;
  outraClinica?: StringNullableFilter;
  participacaoAtividades?: ParticipacaoAtividadeListRelationFilter;
  possuiDoenca?: StringNullableFilter;
  processo?: StringNullableFilter;
  profissao?: StringFilter;
  regulamento?: BooleanNullableFilter;
  religiao?: StringFilter;
  rg?: StringFilter;
  rgOrgaoExpedidor?: StringFilter;
  secao?: StringFilter;
  sexo?: "Masculino" | "Feminino";
  tempoInternacao?: BooleanFilter;
  tiposDrogas?: StringNullableFilter;
  tituloEleitor?: StringFilter;
  uf?: StringFilter;
  zona?: StringFilter;
};
