/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  IsOptional,
  IsInt,
  ValidateNested,
  IsBoolean,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { OcorrenciaCreateNestedManyWithoutAlunosInput } from "./OcorrenciaCreateNestedManyWithoutAlunosInput";
import { ParticipacaoAtividadeCreateNestedManyWithoutAlunosInput } from "./ParticipacaoAtividadeCreateNestedManyWithoutAlunosInput";
import { EnumAlunoSexo } from "./EnumAlunoSexo";
@InputType()
class AlunoCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  cidade!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  cpf!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dataEmissaoRg?: Date | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  dataNascimento!: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dataSaida?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  endereco?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  filiacaoMae!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  filiacaoPai!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  idadeInicioDroga!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  matricula!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  nome!: string;

  @ApiProperty({
    required: false,
    type: () => OcorrenciaCreateNestedManyWithoutAlunosInput,
  })
  @ValidateNested()
  @Type(() => OcorrenciaCreateNestedManyWithoutAlunosInput)
  @IsOptional()
  @Field(() => OcorrenciaCreateNestedManyWithoutAlunosInput, {
    nullable: true,
  })
  ocorrencia?: OcorrenciaCreateNestedManyWithoutAlunosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  outraClinica?: string | null;

  @ApiProperty({
    required: false,
    type: () => ParticipacaoAtividadeCreateNestedManyWithoutAlunosInput,
  })
  @ValidateNested()
  @Type(() => ParticipacaoAtividadeCreateNestedManyWithoutAlunosInput)
  @IsOptional()
  @Field(() => ParticipacaoAtividadeCreateNestedManyWithoutAlunosInput, {
    nullable: true,
  })
  participacaoAtividades?: ParticipacaoAtividadeCreateNestedManyWithoutAlunosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  possuiDoenca?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  processo?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  profissao!: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  regulamento?: boolean | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  religiao!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  rg!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  rgOrgaoExpedidor!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  secao!: string;

  @ApiProperty({
    required: true,
    enum: EnumAlunoSexo,
  })
  @IsEnum(EnumAlunoSexo)
  @Field(() => EnumAlunoSexo)
  sexo!: "Masculino" | "Feminino";

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  tempoInternacao!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tiposDrogas?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  tituloEleitor!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  uf!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  zona!: string;
}
export { AlunoCreateInput };
